# Funding links shown in the "Sponsor" button on your GitHub repo page.
# Uncomment the platforms you use. Full list:
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# github: your-username
# patreon: your-username
# ko_fi: your-username
# open_collective: your-project
# buy_me_a_coffee: your-username
# custom: https://your-site.com/donate
